<?php

namespace App\Models\Assigments;

use Illuminate\Database\Eloquent\Model;
use App\Models\Assigments\TaskAssigment;

class KreNominatif extends Model
{
    // protected $connection = 'mysql_external_dpm';//offline
    protected $connection = 'mysql_external_dpm_online';//online
	protected $table = 'kre_nominatif';
	protected $fillable = [
		'tgl_laporan',
		'no_rekening',
		'kode_kantor',
		'kode_unit',
		'nasabah_id',
		'nama_nasabah',
		'alamat',
		'kecamatan',
		'kab_kota',
		'kota',
		'domisili_alamat',
		'domisili_kecamatan',
		'domisili_kota_kab',
		'domisili_kota',
		'jenis_kelamin',
		'bi_sektor_ekonomi',
		'bi_jenis_penggunaan',
		'kode_chenelling',
		'kode_asuransi',
		'kode_integrasi',
		'kode_produk',
		'kode_produk',
		'kode_keterkaitan',
		'kode_group1',
		'kode_group2',
		'kode_group3',
		'kode_group4',
		'kode_group5',
		'kode_group6',
		'kode_group7',
		'kode_so',
		'rekomendasi_ca',
		'jml_rekomendasi',
		'keterangan_ca',
		'jenis_fasilitas',
		'tgl_realisasi',
		'jml_angsuran',
		'tgl_jatuh_tempo',
		'perpanjangan',
		'type_kredit',
		'suku_bunga_per_tahun',
		'jml_pinjaman',
		'baki_debet',
		'saldo_provisi',
		'saldo_adm',
		'saldo_biaya',
		'baki_debet_netto',
		'jml_map',
		'jml_realisasi',
		'jml_realisasi_ro',
		'jenis_agunan',
		'ikatan_agunan',
		'nilai_taksasi_agunan',
		'kolek_bi',
		'kolek_bi_eom',
		'ft_hari',
		'ft_hari_pokok',
		'ft_hari_bunga',
		'ft_hari_denda',
		'tgl_lunas',
		'debius',
		'tgl_debius',
		'jumlah_debius',
		'saldo_debius',
		'ayda',
		'tgl_ayda',
		'jumlah_ayda',
		'saldo_ayda',
		'jml_diperhitungkan',
		'tgl_macet_terakhir',
		'persen_ppapwd',
		'jml_ppapwd',
		'jml_pyad',
		'jml_pad',
		'sisa_bulan_angsuran',
		'ft_angsuran',
		'deskripsi_agunan',
		'jumlah_angsuran_pokok',
		'jumlah_angsuran_bunga',
		'jumlah_angsuran',
		'jumlah_tunggakan_pokok',
		'jumlah_tunggakan_bunga',
		'jumlah_tunggakan',
		'jumlah_tunggakan_denda',
		'pembayaran',
		'pelunasan',
		'no_rektabungan',
		'setoran_hari_ini',
		'akumulasi_setoran',
		'tagihan_bulan_ini',
		'last_payment',
		'janji_bayar',
		'bucket_bln_lalu',
		'bucket',
		'status_roll',
		'last_update'
	];

	public function Task()
	{
		return $this->belongsTo(MasterAssigmentCollector::class, 'no_rekening', 'no_rekening');
	}
}
